bda_avance_agua_surco:
  name:                 avance_agua_surco
  columns:
    aas_item:           { name: id, constraint: PK, sequence: bda_avance_agua_surco_aas_item_seq }
    car_num_documento:  { name: control_administrativo_riego_id }
    aas_surco_id:       { name: surco_id }
    aas_created_at:     { name: created_at, behavior: created }
    aas_updated_at:     { name: updated_at, behavior: updated }
    aas_deleted_at:     { name: deleted_at, behavior: deleted }

bda_bitacora:
  name:                bitacora
  columns:
    bit_id:            { name: id, constrain: PK, sequence: bda_bitacora_bit_id_seq }
    usr_id:            { name: usuario_id }
    bit_accion:        { name: accion, length: 80 }
    bit_tabla:         { name: tabla, length: 80 }
    bit_registro:      { name: registro }
    bit_observacion:   { name: observaciones, lenght: 1024 }
    bit_fecha:         { name: fecha }

bda_cargo:
  name:                cargo
  columns:
    car_id:            { name: id, constrain: PK, sequence: bda_cargo_car_id_seq }
    car_descripcion:   { name: descripcion, lenght: 80 }
    car_created_at:    { name: created_at, behavior: created }
    car_updated_at:    { name: updated_at, behavior: updated }
    car_deleted_at:    { name: deleted_at, behavior: deleted }